# Change these first
owner: selfomy # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Selfomy One
    url: https://one.selfomy.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Selfomy
  introTitle: "Trạng thái hoạt động của các sản phẩm của Selfomy"
  introMessage: Giúp bạn theo dõi và cập nhật nhanh chóng tình trạng, độ ổn định cũng như lịch bảo trì các sản phẩm của Selfomy. 
  navbar:
    - title: Trạng thái
      href: /uptime
    - title: Về trang chủ
      href: https://selfomy.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
